package id.poliban.ac.mi.customlistview;
import  java.util.ArrayList;
import java.util.List;
public class FoodData {
     static List<food> getallFoods() {
        List<food> data = new ArrayList<>();
        {
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Rujakcingur.jpg/250px-Rujakcingur.jpg","Rujak cingur","Rujak cingur adalah salah satu makanan tradisional yang mudah ditemukan di daerah Jawa Timur, terutama daerah asalnya Surabaya. Dalam bahasa Jawa kata cingur berarti \"mulut\", hal ini merujuk pada bahan irisan mulut atau moncong sapi yang direbus dan dicampurkan ke dalam hidangan. Rujak cingur biasanya terdiri dari irisan beberapa jenis buah seperti timun, kerahi (krai, yaitu sejenis timun khas Jawa Timur), bengkuang, mangga muda, nanas, kedondong, kemudian ditambah lontong, tahu, tempe, bendoyo, cingur, serta sayuran seperti kecambah/taoge, kangkung, dan kacang panjang. Semua bahan tadi dicampur dengan saus atau bumbu yang terbuat dari olahan petis udang, air matang untuk sedikit mengencerkan, gula/gula merah, cabai, kacang tanah yang digoreng, bawang goreng, garam, dan irisan tipis pisang biji hijau yang masih muda (pisang klutuk). Semua saus/bumbu dicampur dengan cara diulek, itu sebabnya rujak cingur juga sering disebut rujak ulek."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Gado_gado.jpg/250px-Gado_gado.jpg","Gado-gado","Gado-gado adalah salah satu makanan yang berasal dari Indonesia yang berupa sayur-sayuran yang direbus dan dicampur jadi satu, dengan bumbu kacang atau saus dari kacang tanah dan yang dihaluskan disertai irisan telur dan pada umumnya banyak yang menambahkan kentang rebus yang sudah dihaluskan untuk saus gado gado kentang rebus dimasak bersamaan dengan bumbu kacang kemudian di atasnya ditaburi bawang goreng. Sedikit emping goreng atau kerupuk (ada juga yang memakai kerupuk udang) juga ditambahkan."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Nasi_Rawon_A.JPG/220px-Nasi_Rawon_A.JPG","Rawon","Rawon adalah masakan Indonesia berupa sup daging berkuah hitam sebagai campuran bumbu khas yang menggunakan kluwek. Rawon, meskipun dikenal sebagai masakan khas Jawa Timur, dikenal pula oleh masyarakat Jawa Tengah sebelah timur (daerah Surakarta)."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Pecel_Hariadhi.JPG/220px-Pecel_Hariadhi.JPG","Pecel","Pecel atau pecal (Hanacaraka: ꦥꦼꦕꦼꦭ꧀) merupakan makanan yang dikombinasikan dengan bumbu sambal kacang sebagai bahan utamanya dan dicampur dengan aneka jenis sayuran. Makanan ini populer terutama di wilayah DI Yogyakarta, Jawa Tengah, dan Jawa Timur."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Rendang_daging_sapi_asli_Padang.JPG/250px-Rendang_daging_sapi_asli_Padang.JPG","Rendang","Rendang atau randang (Jawi: رندڠ) adalah masakan daging dengan bumbu rempah-rempah yang berasal dari Minangkabau. Masakan ini dihasilkan dari proses memasak yang dipanaskan berulang-ulang menggunakan santan sampai kuahnya kering sama sekali. Proses memasaknya memakan waktu berjam-jam (biasanya sekitar empat jam) hingga yang tinggal hanyalah potongan daging berwarna hitam pekat. Dalam suhu ruangan, rendang dapat bertahan hingga berminggu-minggu. Rendang yang dimasak dalam waktu yang lebih singkat dan santannya belum mengering disebut kalio, berwarna cokelat terang keemasan."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Kue_bika_ambon.JPG/220px-Kue_bika_ambon.JPG","Bika Ambon","Bika ambon adalah sejenis penganan asal Indonesia. Terbuat dari bahan-bahan seperti telur, gula, dan santan, bika ambon umumnya dijual dengan rasa pandan, meskipun kini juga tersedia rasa-rasa lainnya seperti durian, keju, dan cokelat. Bika ambon biasanya dapat bertahan dalam kondisi terbaik selama sekitar empat hari karena setelah itu kue tersebut mulai mengeras."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/id/thumb/1/19/Laksan.jpg/220px-Laksan.jpg","Laksan","Laksan adalah makanan khas Palembang yang terbuat dari bahan baku sagu dan ikan. Laksan dibuat dalam bentuk oval dengan rasa yang hampir pempek, tetapi disajikan dengan menggunakan kuah santan."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Penang_laksa.jpg/220px-Penang_laksa.jpg","Lakso/Laksa","Laksa adalah makanan berjenis mi yang ditaruh bumbu dengan kebudayaan Peranakan, yang digabung dengan elemen Tionghoa dan Melayu. Laksa mempunyai beberapa jenis, yang paling dikenal adalah yang berjenis Laksa Penang, bentuk mi-nya bulat putih dan sedikit tebal. Di Indonesia juga terdapat beberapa jenis laksa seperti Laksa Bogor dan Laksa Betawi. Nama Laksa diambil dari bahasa Sanskerta yang mempunyai arti banyak, menunjukkan bahwa mi Laksa dibuat dengan berbagai bumbu."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Kapurung_Luwu.jpg/300px-Kapurung_Luwu.jpg","Kapurung","Kappurung adalah salah satu makanan khas tradisional di Sulawesi Selatan, khususnya masyarakat daerah Luwu (Kota Palopo, Kabupaten Luwu, Luwu Utara, Luwu Timur) Makanan ini terbuat dari sari atau tepung sagu. Di daerah Maluku dikenal dengan nama Papeda. Kappurung dimasak dengan campuran ikan atau daging ayam dan aneka sayuran. Meski makanan tradisional, Kappurung mulai populer. Selain ditemukan di warung-warung khusus di Makassar juga telah masuk ke beberapa restoran, bersanding dengan makanan modern.Di daerah Luwu sendiri nama Kappurung' ini sering juga di sebut Pugalu atau Bugalu."));
            data.add(new food("https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Sop_Konro.JPG/250px-Sop_Konro.JPG","Sop Konro","Sup Konro adalah masakan sup iga sapi khas Indonesia yang berasal dari tradisi Bugis dan Makassar.[1] Sup ini biasanya dibuat dengan bahan iga sapi atau daging sapi.[1][2] Masakan berkuah warna coklat kehitaman ini biasa dimakan dengan burasa dan ketupat yang dipotong-potong terlebih dahulu. Warna gelap ini berasal dari buah kluwek yang memang berwarna hitam. Bumbunya relatif \"kuat\" akibat digunakannya ketumbar. Rasa pedas dan berbumbu ini dibuat dari campuran rempah-rempah, seperti ketumbar, keluwak (buah yang menyebabkan masakan berwarna hitam), sedikit pala, kunyit, kencur, kayu manis, asam, daun lemon, cengkih, dan daun salam"));
            data.add(new food("https://upload.wikimedia.org/wikipedia/id/thumb/d/de/Manday.jpg/220px-Manday.jpg","Manday","Manday, atau Mandai, adalah salah satu jenis lauk alternatif dari daerah Kalimantan Selatan. Mandai disebut juga dengan Mandai Basang atau kulit buah Cempedak yang digoreng. Orang Banjar biasanya menyebut makanan dari kulit cempedak ini dengan Manday tetapi ada juga yang menyebutnya dengan Dami"));
        }
            return data;
    }
}
